name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: 🔄 Deploy via lftp
      run: |
        lftp -u "${{ secrets.NAME }},${{ secrets.PASS }}" ${{ secrets.HOST }} <<EOF
        set ftp:ssl-force true
        set ftp:ssl-protect-data true
        mirror -R ./ /www/cheese_api/
        quit
        EOF
